/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';

import '@stencil/redux';
import '@stencil/state-tunnel';


export namespace Components {

  interface AppDateTime {}
  interface AppDateTimeAttributes extends StencilHTMLAttributes {}

  interface DatePicker {}
  interface DatePickerAttributes extends StencilHTMLAttributes {}
}

declare global {
  interface StencilElementInterfaces {
    'AppDateTime': Components.AppDateTime;
    'DatePicker': Components.DatePicker;
  }

  interface StencilIntrinsicElements {
    'app-date-time': Components.AppDateTimeAttributes;
    'date-picker': Components.DatePickerAttributes;
  }


  interface HTMLAppDateTimeElement extends Components.AppDateTime, HTMLStencilElement {}
  var HTMLAppDateTimeElement: {
    prototype: HTMLAppDateTimeElement;
    new (): HTMLAppDateTimeElement;
  };

  interface HTMLDatePickerElement extends Components.DatePicker, HTMLStencilElement {}
  var HTMLDatePickerElement: {
    prototype: HTMLDatePickerElement;
    new (): HTMLDatePickerElement;
  };

  interface HTMLElementTagNameMap {
    'app-date-time': HTMLAppDateTimeElement
    'date-picker': HTMLDatePickerElement
  }

  interface ElementTagNameMap {
    'app-date-time': HTMLAppDateTimeElement;
    'date-picker': HTMLDatePickerElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
